package de.bwueller.mcgl.constant;

public class Particle {

    public static final String ANGRY_VILLAGER = "angryVillager";
    public static final String BARRIER = "barrier";
    public static final String BLOCK_CRACK = "blockcrack";
    public static final String BLOCK_DUST = "blockdust";
    public static final String BUBBLE = "bubble";
    public static final String CLOUD = "cloud";
    public static final String CRIT = "crit";
    public static final String DAMAGE_INDICATOR = "damageIndicator";
    public static final String DEPTH_SUSPEND = "depthsuspend";
    public static final String DRAGON_BREATH = "dragonbreath";
    public static final String DRIP_LAVA = "dripLava";
    public static final String DROPLET = "droplet";
    public static final String ENCHANTMENT_TABLE = "enchantmenttable";
    public static final String END_ROD = "endRod";
    public static final String EXPLODE = "explode";
    public static final String FIREWORKS_SPARK = "fireworksSpark";
    public static final String FLAME = "flame";
    public static final String FOOTSTEP = "footstep";
    public static final String HAPPY_VILLAGER = "happyVillager";
    public static final String HEART = "heart";
    public static final String HUGE_EXPLOSION = "hugeexplosion";
    public static final String ICON_CRACK = "iconcrack";
    public static final String INSTANT_SPELL = "instantSpell";
    public static final String LARGE_EXPLODE = "largeexplode";
    public static final String LARGE_SMOKE = "largesmoke";
    public static final String LAVA = "lava";
    public static final String MAGIC_CRIT = "magicCrit";
    public static final String MOB_APPEARANCE = "mobappearance";
    public static final String MOB_SPELL = "mobSpell";
    public static final String MOB_SPELL_AMBIENT = "mobSpellAmbient";
    public static final String NOTE = "note";
    public static final String PORTAL = "portal";
    public static final String RED_DUST = "reddust";
    public static final String SLIME = "slime";
    public static final String SMOKE = "smoke";
    public static final String SNOWBALL_POOF = "snowballpoof";
    public static final String SNOW_SHOVEL = "snowshovel";
    public static final String SPELL = "spell";
    public static final String SPLASH = "splash";
    public static final String SUSPEND = "suspend";
    public static final String SWEEP_ATTACK = "sweepAttack";
    public static final String TAKE = "take";
    public static final String TOWNAURA = "townaura";
    public static final String WAKE = "wake";
    public static final String WITCH_MAGIC = "witchMagic";
}
